// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBI4nZF065gYBFadTtHTDT73yLls2cf9ns',
    appId: '1:630548785812:web:faeb5e4131a840fc88a281',
    messagingSenderId: '630548785812',
    projectId: 'mediconverse',
    authDomain: 'mediconverse.firebaseapp.com',
    storageBucket: 'mediconverse.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC5YuC3ZRmPgV-89kXM9Zua7deGt3Mr2lk',
    appId: '1:630548785812:android:532b3407abd7b9e888a281',
    messagingSenderId: '630548785812',
    projectId: 'mediconverse',
    storageBucket: 'mediconverse.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBI4nZF065gYBFadTtHTDT73yLls2cf9ns',
    appId: '1:630548785812:web:7ad81d3e2ece085b88a281',
    messagingSenderId: '630548785812',
    projectId: 'mediconverse',
    authDomain: 'mediconverse.firebaseapp.com',
    storageBucket: 'mediconverse.firebasestorage.app',
  );
}
